export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const EDIT_CAMPAIGN = 'EDIT_CAMPAIGN';